spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientes_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin
    devtools:
      remote:
        secret: 123

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true

  jackson:
    default-property-inclusion: NON_NULL
jwt:
  secret: _jwtteste_
  expiration: 30

server:
  port: 8081
 error:
  include-message: always